fix: remove Showing... count message
ethereum/geth-website pull request #118
Opened 2022-12-02 16:28 UTC by nhsz

This PR fixes #80 by removing the number of releases displayed count message

2022-12-02 23:38 UTC, wackerow requested changes
Left a small fix to use our chakra theme variables to make the border color light/dark mode responsive. Then should be good to go!

2022-12-02 23:38 UTC, wackerow commented on src/pages/downloads.tsx
> +                  borderLeft={{ base: 'none', md: '2px solid #06fece' }}
```suggestion
                  borderLeft={{ base: 'none', md: '2px solid var(--chakra-colors-primary)' }}
```

2022-12-02 23:38 UTC, wackerow commented on src/pages/downloads.tsx
> +                  borderLeft={{ base: 'none', md: '2px solid #06fece' }}
```suggestion
                  borderLeft={{ base: 'none', md: '2px solid var(--chakra-colors-green-200)' }}
```

2022-12-02 23:38 UTC, wackerow commented on src/pages/downloads.tsx
> +                  borderLeft={{ base: 'none', md: '2px solid #06fece' }}
Actually:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/54227730/205409064-24bd9ed7-eb05-4dcf-98ad-417c207a7757.png">

This needs to be light/dark mode responsive... we should be using `primary` here
```suggestion
                  borderLeft={{ base: 'none', md: '2px solid var(--chakra-colors-primary)' }}
```

2022-12-05 15:22 UTC, nhsz commented
> https://deploy-preview-118--melodious-puffpuff-8e1109.netlify.app

Thx, updated with the suggestions 👌

2022-12-05 16:33 UTC, wackerow approved these changes

2022-12-05 16:39 UTC, merged