[WIP] Mobile menu
ethereum/geth-website pull request #39
Opened 2022-11-18 03:07 UTC by wackerow

2022-11-22 06:40 UTC, corwintines approved these changes
LGTM, I pushed a couple commits to abstract some duplicate code I saw, and setup for search, but nice one!

2022-11-22 18:13 UTC, wackerow commented
@corwintines 
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/54227730/203390066-914fbe27-632a-4259-9476-637e102729a6.png">
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/54227730/203390219-d1a8d70b-fd69-4e66-80eb-0017da22a056.png">

Getting broken styling in the nav bar now. Just noting the styling for those buttons is different for the nav vs the mobile menu that I added, that was why I kept them separated.

2022-11-22 18:32 UTC, corwintines commented
@wackerow pushed up a fix for that

2022-11-22 22:03 UTC, wackerow commented
Cool looks good, would approve it but it was my PR

2022-11-23 15:39 UTC, nhsz requested changes
Nice! Thanks @wackerow. Some adjustments needed to match the design on figma.

2022-11-23 15:39 UTC, nhsz commented on src/components/UI/HeaderButtons.tsx
> +              downloads
text [should be centered](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=885%3A8258&t=Ic6WpLw62Cylvxti-0)

2022-11-23 15:39 UTC, nhsz commented on src/components/UI/HeaderButtons.tsx
> +              documentation
text [should be centered](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=885%3A8258&t=Ic6WpLw62Cylvxti-0)

2022-11-23 15:39 UTC, nhsz commented on src/components/UI/search/Search.tsx
> +      <InputGroup>
we use [less padding for search input](text [should be centered](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=885%3A8258&t=Ic6WpLw62Cylvxti-0))

2022-11-23 15:39 UTC, nhsz commented on src/components/layouts/MobileMenu.tsx
> +          <Flex
container reaches the botto of the screen and [should have bottom padding too](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=885%3A8258&t=Ic6WpLw62Cylvxti-0)

<img width="376" alt="Screen Shot 2022-11-23 at 12 37 52" src="https://user-images.githubusercontent.com/948922/203587475-f4664445-fff0-41e6-b405-e629cc8116fe.png">

2022-11-23 19:57 UTC, merged