Limit SVG width on mobile [Fixes #38]
ethereum/geth-website pull request #41
Opened 2022-11-20 16:51 UTC by wackerow

## Description
- Adds a base case (mobile) of 100% width for GopherDownloads SVG component on /downloads page
- Removes unneeded padding on container.

## Screenshot
@ (320px wide)
<img width="320" alt="image" src="https://user-images.githubusercontent.com/54227730/202914337-df81b773-9876-4298-9992-a8ef25f8b1ec.png">

## Related issue
- [Fixes #38]

2022-11-22 01:14 UTC, nhsz commented
Padding is still required for tablet/desktop (`md` and higher)

<img width="1070" alt="Screen Shot 2022-11-21 at 22 13 27" src="https://user-images.githubusercontent.com/948922/203190393-4edf18df-4cd3-45f8-9eef-d0036f4a430a.png">

2022-11-22 03:58 UTC, nhsz requested changes
Thanks @wackerow, seems we need some minor adjustments related to the padding and it'll be ready to go 😎

2022-11-22 03:58 UTC, nhsz commented on src/components/UI/downloads/DownloadsHero.tsx
> -            py={{ base: 0 }}
Padding is still required for [tablet/desktop ](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=1043%3A8879&t=rol3tipDhhgzwHrC-0)(`md` and higher). Seems like [padding for the content in mobile](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=1077%3A9400&t=rol3tipDhhgzwHrC-0) should be updated too 

<img width="1070" alt="Screen Shot 2022-11-21 at 22 13 27" src="https://user-images.githubusercontent.com/948922/203190393-4edf18df-4cd3-45f8-9eef-d0036f4a430a.png">

2022-11-22 04:58 UTC, corwintines approved these changes
Pushed something to clean this up (my own code from before, just noticed it), but added some padding from the change request

2022-11-24 01:28 UTC, nhsz approved these changes

2022-11-24 01:29 UTC, merged