Darker code bg as per figma #52
ethereum/geth-website pull request #55
Opened 2022-11-25 23:49 UTC by ai-slave

2022-11-30 05:59 UTC, wackerow requested changes
If we remove the `width` addition, the other change lgtm, thanks @ai-slave!

2022-11-30 05:59 UTC, wackerow commented on src/components/UI/downloads/SpecificVersionsSection.tsx
> +        width={{ base: 'auto', md: '300px' }}
I think this has been fixed with #64

2022-11-30 05:59 UTC, wackerow commented on src/components/UI/downloads/SpecificVersionsSection.tsx
> +        width={{ base: 'auto', md: '300px' }}
```suggestion
```

2022-11-30 06:00 UTC, wackerow approved these changes

2022-11-30 13:38 UTC, nhsz commented
Closing as this was already fixed

2022-12-09 21:55 UTC, wackerow commented
Agree.. @nhsz issue #52 has not been fixed yet, and this PR would fix it:
<img src="https://user-images.githubusercontent.com/1120748/204034045-67e08188-2fc2-44f4-9646-0466ba21c6bd.png" />

That issue requests that the code background be switched to use `gray.100` instead of `gray.200`.. Going to re-open this.

2022-12-09 21:58 UTC, wackerow commented
Sorry, my bad. Got these flipped—source of truth says to use `gray.200` which is what master shows. Closing back out

2022-12-09 21:58 UTC, closed without merging